{% set name = "meson" %}
{% set version = "0.46.1" %}
{% set sha256 = "0c6f39bdc7153fd24cadf07e57a4b9527755d292641126db85c1473babd0bdc9" %}


package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed meson

requirements:
  build:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - ninja >=1.8.2

test:
  commands:
    - meson -h

about:
  home: http://mesonbuild.com
  license: Apache 2
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'The Meson Build System'
  doc_url: http://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - SoapZA
