{% set name = "meson" %}
{% set version = "0.55.1" %}
{% set sha256 = "3b5741f884e04928bdfa1947467ff06afa6c98e623c25cef75adf71ca39ce080" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # See conda-forge/glib-feedstock#40 for documentation regarding the RPATH patch
  patches:
    - 0001-Only-fix-RPATH-if-install_rpath-is-not-empty.patch
    - windows-reexec.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.5.2
    - setuptools
    - pip
  run:
    - python >=3.5.2
    - ninja >=1.8.2
    - setuptools

test:
  commands:
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: https://mesonbuild.com
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: The Meson Build System
  doc_url: https://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
