{% set version = "1.5.0rc1" %}

package:
  name: meson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/meson/meson-{{ version }}.tar.gz
  sha256: 601e4cf0db75372a8e65b95c958dd7336f1af85d4dfd06e8d608c23ea68c3e08
  patches:
    # See conda-forge/glib-feedstock#40 for documentation regarding the RPATH patch
    - patches/0001-Only-fix-RPATH-if-install_rpath-is-not-empty.patch
    # backport https://github.com/mesonbuild/meson/pull/13323
    - patches/0002-WIP-add-initial-support-for-llvm-flang.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - meson = mesonbuild.mesonmain:main


requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - ninja >=1.8.2
    - setuptools

test:
  commands:
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: https://mesonbuild.com
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: The Meson Build System
  doc_url: https://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
    - wolfv
    - tschoonj
    - rgommers
    - h-vetinari
