{% set version = "1.6.0rc1" %}

package:
  name: meson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/meson/meson-{{ version }}.tar.gz
  sha256: c1693ced1de6754641dd2ef31fdfb358fe1df614190678829f5342f04b156ccb
  patches:
    # See conda-forge/glib-feedstock#40 for documentation regarding the RPATH patch
    - patches/0001-Only-fix-RPATH-if-install_rpath-is-not-empty.patch
    # revert https://github.com/mesonbuild/meson/commit/5399d3de02cb0f92e334f3f5f61cf0aa8521ac63
    # as exploratory fix for https://github.com/mesonbuild/meson/issues/13772
    - patches/0002-Revert-compilers-detect-remove-unsupported-cpp-flag-.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - meson = mesonbuild.mesonmain:main


requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - ninja >=1.8.2
    - setuptools

test:
  commands:
    - meson -h
    - meson -v
    - meson --internal delsuffix . nomatchqqq  # test reexecution (GitHub issue #11)

about:
  home: https://mesonbuild.com
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: The Meson Build System
  doc_url: https://mesonbuild.com
  dev_url: https://github.com/mesonbuild/meson

extra:
  recipe-maintainers:
    - dirmeier
    - pkgw
    - SoapZA
    - wolfv
    - tschoonj
    - rgommers
    - h-vetinari
